In [4]:
import random
import pandas as pd

In [5]:
def generate_address():
    # Function to generate a random address
    streets = ['Rue de Rivoli', 'Avenue des Champs-Élysées', 'Boulevard Saint-Germain', 'Rue Saint-Honoré', 'Rue de la Paix', 
               'Avenue Montaigne', 'Rue de la République', 'Boulevard Haussmann', 'Rue de Vaugirard', 'Rue du Faubourg Saint-Honoré']
    return f'{random.randint(1, 200)} {random.choice(streets)}'

def generate_district():
    # Function to generate a random district/arrondissement
    return random.randint(1, 20)

def generate_zipcode():
    # Function to generate a random zipcode
    return f'75{random.randint(1, 20):02d}'

def generate_rent():
    # Function to generate a random rent
    return random.randint(1000, 10000)

def generate_cost():
    # Function to generate a random cost of property
    return random.randint(100000, 5000000)

def generate_maintenance():
    # Function to generate a random maintenance cost
    # 10% of the rent of the cost of property
    return random.randint(30, 200)

def generate_rooms():
    # Function to generate a random number of rooms
    return random.randint(1, 5)

def generate_size():
    # Function to generate a random size in square feet
    return random.randint(300, 2000)

def generate_property_type():
    # Function to generate a random property type
    return random.choice(['Apartment', 'Duplex', 'Villa'])

def co_living():
    # Returns wether Co-living is allowed or not
    return random.randint(0 , 1)

def are_pets_allowed():
    # Returns wether pets are  allowed or not
    return random.randint(0 , 1)

def lease_duration():
    # Returns the lease duration in months
    return random.randint(1 , 36)

# https://www.w3schools.com/python/ref_random_uniform.asp
# Paris co-ordinates are googled
def generate_latitude():
    return round(random.uniform(48.80, 48.90), 6)

def generate_longitude():
    return round(random.uniform(2.25, 2.45), 6)

In [6]:
# Generate data
data = {
    'Address': [generate_address() for _ in range(500)],
    'District/Arrondissement': [generate_district() for _ in range(500)],
    'Zipcode': [generate_zipcode() for _ in range(500)],
    'Rent': [generate_rent() for _ in range(500)],
    'Cost': [generate_cost() for _ in range(500)],
    'Maintenance': [generate_maintenance() for _ in range(500)],
    'Number of rooms': [generate_rooms() for _ in range(500)],
    'Size': [generate_size() for _ in range(500)],
    'Property Type': [generate_property_type() for _ in range(500)],
    'Co-Living': [co_living() for _ in range(500)],
    'Pets allowed': [are_pets_allowed() for _ in range(500)],
    'Lease Duration': [lease_duration() for _ in range(500)],
    'Latitude': [generate_latitude() for _ in range(500)],
    'Longitude': [generate_longitude() for _ in range(500)]
}

# Create DataFrame
df = pd.DataFrame(data)
df.head()

,Address,District/Arrondissement,Zipcode,Rent,Cost,Maintenance,Number of rooms,Size,Property Type,Co-Living,Pets allowed,Lease Duration,Latitude,Longitude
0,65 Rue de Rivoli,1,7504,1831,788335,123,1,1492,Apartment,0,1,6,48.825778,2.313958
1,178 Rue de la République,16,7509,7687,2762283,121,1,816,Villa,0,1,13,48.863504,2.294148
2,129 Avenue Montaigne,9,7504,1111,356270,99,2,1949,Villa,0,0,11,48.874340,2.346008
3,196 Rue Saint-Honoré,12,7515,4263,3408001,153,3,1454,Villa,1,1,6,48.880012,2.442670
4,112 Rue de la Paix,18,7516,1714,131036,79,3,1713,Villa,0,0,5,48.870575,2.437243

In [7]:
preference_data = {
    'Address': [generate_address() for _ in range(100)],
    'District/Arrondissement': [generate_district() for _ in range(100)],
    'Number of rooms': [generate_rooms() for _ in range(100)],
    'Size': [generate_size() for _ in range(100)],
    'Property Type': [generate_property_type() for _ in range(100)],
    'Lease_duration': [lease_duration() for _ in range(100)],
    'Co-Living': [co_living() for _ in range(100)],
    'Rent': [generate_rent() for _ in range(100)],
    'Pets allowed': [are_pets_allowed() for _ in range(100)]
}

pf_df = pd.DataFrame(preference_data)
pf_df.head()

,Address,District/Arrondissement,Number of rooms,Size,Property Type,Lease_duration,Co-Living,Rent,Pets allowed
0,79 Rue de la Paix,11,4,632,Duplex,26,0,5407,0
1,10 Boulevard Saint-Germain,13,3,614,Duplex,7,0,4203,0
2,12 Avenue des Champs-Élysées,4,5,551,Villa,30,0,6628,0
3,57 Avenue des Champs-Élysées,18,4,1732,Villa,21,0,2858,1
4,52 Boulevard Saint-Germain,8,2,351,Duplex,20,0,8899,1

In [8]:
df.to_csv('Synthetic_Data.csv', index=False)
pf_df.to_csv('Preferences.csv', index=False)